### ISSUE TITLE
Updating to version=5.2.5-SNAPSHOT in Kevoree editor fails with exceptions

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#54]
06:34 INFO: JavaNode received a new Model to apply from /groups[sync]
06:34 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.ws,version=5.2.5-SNAPSHOT]
06:39 INFO: Resolved in 4975ms
06:39 ERROR:
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:220)
        at java.util.zip.ZipFile.<init>(ZipFile.java:150)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.kevoree.kcl.impl.JarIndexDB.loadJar(JarIndexDB.java:103)
        at org.kevoree.kcl.impl.FlexyClassLoaderImpl.load(FlexyClassLoaderImpl.java:119)
        at org.kevoree.microkernel.impl.KevoreeMicroKernelImpl.put(KevoreeMicroKernelImpl.java:70)
        at org.kevoree.bootstrap.kernel.KevoreeCLKernel.installDeployUnit(KevoreeCLKernel.java:97)
        at org.kevoree.library.java.command.AddDeployUnit.execute(AddDeployUnit.java:50)
        at org.kevoree.core.impl.deploy.KevoreeSeqDeployPhase.runPhase(KevoreeSeqDeployPhase.kt:43)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:79)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.execute(PrimitiveCommandExecutionHelper.kt:44)
        at org.kevoree.core.impl.KevoreeCoreBean.internal_update_model(KevoreeCoreBean.java:408)
        at org.kevoree.core.impl.KevoreeCoreBean$UpdateModelRunnable.run(KevoreeCoreBean.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
06:39 INFO: Stopping /groups[sync]
06:39 WARN: Error during execution of org.kevoree.library.java.command.UpgradeInstance@70beaf29
06:39 WARN: JavaSENode is aborting last update...
06:39 ERROR: Error during rollback
java.lang.NullPointerException
        at org.kevoree.library.java.command.RemoveInstance.undo(RemoveInstance.java:45)
        at org.kevoree.library.java.command.UpgradeInstance.undo(UpgradeInstance.java:45)
        at org.kevoree.core.impl.deploy.KevoreeSeqDeployPhase.rollBack(KevoreeSeqDeployPhase.kt:80)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:104)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:91)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:91)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:91)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:91)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.executeStep(PrimitiveCommandExecutionHelper.kt:91)
        at org.kevoree.core.impl.deploy.PrimitiveCommandExecutionHelper.execute(PrimitiveCommandExecutionHelper.kt:44)
        at org.kevoree.core.impl.KevoreeCoreBean.internal_update_model(KevoreeCoreBean.java:408)
        at org.kevoree.core.impl.KevoreeCoreBean$UpdateModelRunnable.run(KevoreeCoreBean.java:166)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
06:39 INFO: Starting /groups[sync]
06:39 WARN: JavaSENode update aborted in 5600 ms
06:39 INFO: End deploy result=false-5476
06:39 INFO: WSGroup "sync" update result: false
10:35 INFO: Stopping Kevoree
10:35 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.channels,version=5.2.4]
10:36 INFO: Resolved in 5ms
10:36 INFO: Resolving ............. /packages[com]/packages[softwareag]/packages[research]/packages[heads]/packages[tutorial]/deployUnits[hashcode=,name=movemessage,version=1.0.0-SNAPSHOT]
10:37 INFO: Resolved in 1151ms
10:37 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.javaNode,version=5.2.4]
10:37 INFO: Resolved in 2ms
10:37 INFO: Resolving ............. /packages[io]/packages[undertow]/deployUnits[hashcode=,name=undertow-core,version=1.2.0.Beta8]
10:37 INFO: Resolved in 3ms
10:37 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[xnio]/deployUnits[hashcode=,name=xnio-nio,version=3.3.0.Final]
10:37 INFO: Resolved in 57ms
10:37 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[xnio]/deployUnits[hashcode=,name=xnio-api,version=3.3.0.Final]
10:37 INFO: Resolved in 30ms
10:37 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[logging]/deployUnits[hashcode=,name=jboss-logging,version=3.1.4.GA]
10:37 INFO: Resolved in 2ms
10:37 INFO: Resolving ............. /packages[fr]/packages[braindead]/deployUnits[hashcode=,name=wsmsgbroker-client,version=1.0.2]
10:37 INFO: Resolved in 71ms
10:37 INFO: Resolving ............. /packages[com]/packages[google]/packages[code]/packages[gson]/deployUnits[hashcode=,name=gson,version=2.3]
10:37 INFO: Resolved in 6ms
10:37 INFO: Resolving ............. /packages[org]/packages[java-websocket]/deployUnits[hashcode=,name=Java-WebSocket,version=1.3.0]
10:37 INFO: Resolved in 10ms
10:38 INFO: Stopping /nodes[node2]/components[myComp]
10:38 INFO: Stopping /groups[sync]
10:38 INFO: Stopping /hubs[chan1]
10:38 INFO: Stopping /hubs[chan2]
10:38 INFO: Stopping node type of node2
10:38 INFO: Kevoree core stopped
10:38 INFO: Stopped.

**Comment by maxleiko** [comment]
Thanks for the feedback, this is an issue. I'm working on a fix.

**Comment by skorsky** [comment]
After the exceptions above, the nodes consume much CPU power. System response is slow.

**Comment by brice-morin** [comment]
@maxleiko what is status here?
