### ISSUE TITLE
Tutorial 2, SAG contribution:  java.net.BindException

### ISSUE THREAD

**Issue by skorsky** [HEADS-project/training#64]
I get a java.net.BindException: Address already in use: bind when starting one of my 3 Java nodes.
I don't know which port is required.

Complete stdout:
```
[INFO] Scanning for projects...
[INFO]
[INFO] Using the builder org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder with a thread count of 1
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Kevoree :: SAG 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- org.kevoree.tools.mavenplugin:5.2.5:run (default-cli) @ movemessage ---
[INFO] Manually install file:D:\Users\mask\git\skorsky\training\2.Kevoree_Basics\6.Contrib\SAG\target\classes for mvn:com.softwareag.research.heads.tutorial:movemessage:1.0.0-SNAPSHOT
00:00 INFO: Bootstrap Kevoree node : node0, version 5.2.5
00:00 INFO: Load Bootstrap model from D:\Users\mask\git\skorsky\training\2.Kevoree_Basics\6.Contrib\SAG\target\classes\KEV-INF\lib.json
00:00 INFO: Request=JavaNode,JavaNode,JavaNode,com.softwareag.research.heads.tutorial.MoveMessage,com.softwareag.research.heads.tutorial.MoveMessage,com.softwareag.research.heads.tutorial.MoveMessage,
WSGroup,WSChan,WSChan,WSChan,
00:01 INFO: Resolved 69 typeDefinitions from Kevoree Registry http://registry.kevoree.org/v5/ (JavaNode/5.2.0,WSGroup/5.2.1-SNAPSHOT,JavaNode/5.0.3,JavaNode/5.2.1,JavaNode/5.0.4,JavaNode/5.2.2,JavaNod
e/5.0.5,JavaNode/5.2.3,WSGroup/5.2.4-SNAPSHOT,WSGroup/5.0.8-SNAPSHOT,JavaNode/5.0.6-SNAPSHOT,JavaNode/5.2.4,JavaNode/5.0.6,WSGroup/5.0.5-SNAPSHOT,JavaNode/5.0.7,JavaNode/5.1.4-SNAPSHOT,JavaNode/5.2.2-
SNAPSHOT,WSChan/5.2.3-SNAPSHOT,JavaNode/5.2.5-SNAPSHOT,WSGroup/5.1.2,WSGroup/5.1.3,WSGroup/5.1.4,WSGroup/5.1.0,WSGroup/5.1.1,JavaNode/5.0.3-SNAPSHOT,JavaNode/5.1.1-SNAPSHOT,WSChan/5.1.4-SNAPSHOT,JavaN
ode/5.1.2-SNAPSHOT,WSGroup/5.2.2-SNAPSHOT,WSGroup/5.0.7,WSGroup/5.2.3-SNAPSHOT,WSChan/5.2.4-SNAPSHOT,WSGroup/5.1.2-SNAPSHOT,WSGroup/5.0.7-SNAPSHOT,JavaNode/5.2.3-SNAPSHOT,JavaNode/5.1.0,JavaNode/5.0.7
-SNAPSHOT,JavaNode/5.1.1,JavaNode/5.1.2,JavaNode/5.1.3,JavaNode/5.2.1-SNAPSHOT,WSGroup/0.1.0,WSGroup/5.0.3,WSGroup/5.2.1,WSGroup/5.2.2,WSGroup/5.0.4,WSGroup/5.0.3-SNAPSHOT,WSGroup/5.0.5,WSGroup/5.2.3,
WSGroup/5.0.6,WSGroup/5.2.4,WSChan/2.2.3-SNAPSHOT,WSGroup/5.1.1-SNAPSHOT,WSGroup/5.2.0,JavaNode/5.0.8-SNAPSHOT,JavaNode/5.2.4-SNAPSHOT,WSChan/5.2.5-SNAPSHOT,WSChan/5.2.4,WSChan/5.2.3,WSChan/5.2.2,WSCh
an/5.2.1,WSChan/5.2.0,WSChan/5.2.2-SNAPSHOT,WSGroup/5.2.5-SNAPSHOT,WSGroup/5.1.4-SNAPSHOT,JavaNode/5.0.5-SNAPSHOT,WSGroup/5.0.4-SNAPSHOT,JavaNode/5.0.4-SNAPSHOT,WSChan/5.2.1-SNAPSHOT)
00:01 WARN: Try to select snapshot in best effort mode for com.softwareag.research.heads.tutorial.MoveMessage
00:01 WARN: Founded: MoveMessage:1.0.0-SNAPSHOT
00:01 WARN: Try to select snapshot in best effort mode for com.softwareag.research.heads.tutorial.MoveMessage
00:01 WARN: Founded: MoveMessage:1.0.0-SNAPSHOT
00:01 WARN: Try to select snapshot in best effort mode for com.softwareag.research.heads.tutorial.MoveMessage
00:01 WARN: Founded: MoveMessage:1.0.0-SNAPSHOT
00:02 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.javaNode,version=5.2.4]
00:02 INFO: Resolved in 3ms
00:02 INFO: JavaNode, changing LOG level to INFO
00:02 INFO: Starting node type of node0
00:03 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[library]/packages[java]/deployUnits[hashcode=,name=org.kevoree.library.java.ws,version=5.2.4]
00:03 INFO: Resolved in 3ms
00:03 INFO: Resolving ............. /packages[io]/packages[undertow]/deployUnits[hashcode=,name=undertow-core,version=1.2.0.Beta8]
00:03 INFO: Resolved in 1ms
00:03 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[xnio]/deployUnits[hashcode=,name=xnio-nio,version=3.3.0.Final]
00:03 INFO: Resolved in 1ms
00:03 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[xnio]/deployUnits[hashcode=,name=xnio-api,version=3.3.0.Final]
00:03 INFO: Resolved in 2ms
00:03 INFO: Resolving ............. /packages[org]/packages[jboss]/packages[logging]/deployUnits[hashcode=,name=jboss-logging,version=3.1.4.GA]
00:03 INFO: Resolved in 2ms
00:03 INFO: Resolving ............. /packages[fr]/packages[braindead]/deployUnits[hashcode=,name=wsmsgbroker-client,version=1.0.2]
00:03 INFO: Resolved in 2ms
00:03 INFO: Resolving ............. /packages[com]/packages[google]/packages[code]/packages[gson]/deployUnits[hashcode=,name=gson,version=2.3]
00:03 INFO: Resolved in 2ms
00:03 INFO: Resolving ............. /packages[org]/packages[java-websocket]/deployUnits[hashcode=,name=Java-WebSocket,version=1.3.0]
00:03 INFO: Resolved in 2ms
00:03 INFO: Add instance /nodes[node0]/components[myComp]
00:03 INFO: Add instance /groups[sync]
00:03 INFO: Add instance /hubs[chan2]
00:03 INFO: Add instance /hubs[chan0]
00:03 INFO: Bind /nodes[node0]/components[myComp]/provided[inQueue] /hubs[chan2]
00:03 INFO: Bind /nodes[node0]/components[myComp]/required[outQueue] /hubs[chan0]
00:03 INFO: Starting /nodes[node0]/components[myComp]
00:03 INFO: Start with node Id A, myComp, node0
00:03 INFO: Starting /groups[sync]
MΣr 03, 2015 4:37:52 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.0.Final
MΣr 03, 2015 4:37:52 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.0.Final
00:04 ERROR: Kevoree Group Instance Start Error !
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.kevoree.library.java.wrapper.GroupWrapper.kInstanceStart(GroupWrapper.java:20)
        at org.kevoree.library.java.command.StartStopInstance.run(StartStopInstance.java:54)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
        at io.undertow.Undertow.start(Undertow.java:183)
        at org.kevoree.library.WSGroup.startWSGroup(WSGroup.java:229)
        ... 7 more
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.Net.bind(Net.java:428)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
        at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
        at io.undertow.Undertow.start(Undertow.java:137)
        ... 8 more
00:04 WARN: Error during execution of StartStopInstance sync start
00:04 WARN: JavaSENode is aborting last update...
00:04 INFO: Stopping /hubs[chan0]
00:04 INFO: Stopping /hubs[chan2]
00:04 INFO: Stopping /groups[sync]
00:04 INFO: Stopping /nodes[node0]/components[myComp]
00:04 INFO: Stop node A
00:04 INFO: Remove instance /hubs[chan0]
00:04 INFO: Remove instance /hubs[chan2]
00:04 INFO: Remove instance /groups[sync]
00:04 INFO: Remove instance /nodes[node0]/components[myComp]
00:04 WARN: JavaSENode update aborted in 1584 ms
00:04 INFO: End deploy result=false-1594
00:04 INFO: Bootstrap completed
```

**Comment by maxleiko** [comment]
Kevoree uses port 9000 by default. It is probably this one that isn't available.

**Comment by skorsky** [comment]
not reproducible.

**Comment by brice-morin** [comment]
It can typically happen if you mvn kev:run a second time before properly killing the first kevoree runtime.
